version: 2.1  # Aseguramos que la versión sea 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.3  # Uso de la orb de SonarCloud

executors:
  python-executor:
    docker:
      - image: circleci/python:3.8  # Usamos la imagen de Python que ya tiene Python 3.8
        environment:
          SONAR_TOKEN: ${SONAR_TOKEN}  # Añadimos el token para SonarCloud

jobs:
  build:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y python3-pip
            pip install -r requirements.txt
      - run:
          name: Run Lint
          command: |
            pip install flake8
            flake8 .  # Linting en la raíz del proyecto
      - run:
          name: Run Tests
          command: |
            pip install pytest pytest-cov
            pytest --cov=. tests/  # Cambiamos cobertura a '.' para cubrir el directorio correcto
      - sonarcloud/scan:  # Uso de la orb para ejecutar el análisis de SonarCloud
          project-key: "voydelau28_practica_cicd"  # El key de tu proyecto en SonarCloud
          organization: "voydelau28"  # Tu organización en SonarCloud

workflows:
  build-and-test:
    jobs:
      - build
