version: 2.1

executors:
  python-java-executor:
    docker:
      - image: circleci/openjdk:17-jdk-buster  # Imagen oficial de CircleCI con Java 17

jobs:
  build:
    executor: python-java-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Python 3.8 and Pip
          command: |
            sudo apt-get update && sudo apt-get install -y python3.8 python3.8-distutils
            curl https://bootstrap.pypa.io/get-pip.py | sudo python3.8
      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: Run Lint
          command: |
            pip install flake8
            flake8 .
      - run:
          name: Run Tests
          command: |
            pip install pytest pytest-cov
            pytest --cov=. tests/
      - run:
          name: SonarCloud Scan
          command: |
            sonar-scanner \
              -Dsonar.projectKey=voydelau28_practica_cicd \
              -Dsonar.organization=voydelau28 \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=$SONAR_TOKEN
      - run:
          name: GitGuardian Scan
          command: |
            pip install gitguardian
            ggshield scan repo .

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
