version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0

jobs:
  test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Instalar dependencias
          command: |
            pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Ejecutar pruebas
          command: pytest --cov=. --cov-report xml:coverage.xml
      - run:
          name: Ejecutar linting
          command: flake8 .
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: coverage.xml
      - sonarcloud/scan:
          organization: "voydelau28"
          projectKey: "voydelau28_practica_cicd"
          token: $SONAR_TOKEN

  publish_docker_image:
    docker:
      - image: cimg/python:3.9
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build Docker image
          command: docker build -t voydeuser/mi-app:latest .
      - run:
          name: Login to Docker Hub
          command: |
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      - run:
          name: Push Docker image to Docker Hub
          command: docker push voydeuser/mi-app:latest

workflows:
  version: 2.1
  workflow_test:
    jobs:
      - test
      - publish_docker_image
