version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0

jobs:
  build:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Instalar dependencias
          command: |
            pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Ejecutar pruebas
          command: |
            pytest --cov=backend --cov-report xml:coverage.xml
      - run:
          name: Ejecutar linting
          command: |
            flake8 .
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: coverage.xml
      - sonarcloud/scan:
          setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t voydelau28/myapp:latest .
      - run:
          name: Test Docker image
          command: docker run --rm voydelau28/myapp:latest pytest

  publish:
    docker:
      - image: cimg/python:3.9
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build Docker image
          command: docker build -t voydeuser/myapp:latest .
      - run:
          name: Login to Docker Hub
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - run:
          name: Push Docker image to Docker Hub
          command: docker push voydeuser/myapp:latest

workflows:
  version: 2.1
  workflow_build:
    jobs:
      - build