version: 2.1

executors:
  python-executor:
    docker:
      - image: sonarsource/sonar-scanner-cli:latest  # Imagen que ya contiene SonarScanner

jobs:
  build:
    executor: python-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Upgrade pip
          command: python -m pip install --upgrade pip
      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: Run Lint
          command: |
            pip install flake8
            flake8 .
      - run:
          name: Run Tests
          command: |
            pip install pytest pytest-cov
            pytest --cov=. tests/
      - run:
          name: SonarCloud Scan
          command: |
            sonar-scanner \
              -Dsonar.projectKey=voydelau28_practica_cicd \
              -Dsonar.organization=voydelau28 \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=$SONAR_TOKEN
      - run:
          name: GitGuardian Scan
          command: |
            pip install gitguardian
            ggshield scan repo .

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
