version: 2.1

orbs:
  gitguardian: gitguardian/ggshield@1.4.0  # A침adiendo GitGuardian Orb

executors:
  python-executor:
    docker:
      - image: circleci/python:3.8
    working_directory: ~/repo

jobs:
  build:
    executor: python-executor
    steps:
      - checkout
      - setup_remote_docker  # Usamos la configuraci칩n predeterminada de Docker sin especificar la versi칩n
      - run:
          name: Update pip
          command: |
            python -m pip install --upgrade pip
      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: Install flake8
          command: |
            pip install flake8
      - run:
          name: Run Lint
          command: |
            flake8 .
      - run:
          name: Run Tests
          command: |
            pip install pytest pytest-cov
            pytest --cov=. tests/
      - gitguardian/scan:  # A침adir escaneo de secretos con GitGuardian
          path: .
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker Image
          command: |
            docker build -t voydeuser/myapp:latest .
      - run:
          name: Push Docker Image
          command: |
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            docker push voydeuser/myapp:latest

workflows:
  build-and-test:
    jobs:
      - build
