version: 2.1

executors:
  python-executor:
    docker:
      - image: circleci/python:3.8

jobs:
  build:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Update pip
          command: |
            python -m pip install --upgrade pip  # Actualizamos pip a la versión más reciente
      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: Install flake8
          command: |
            pip install flake8
      - run:
          name: Run Lint
          command: |
            flake8 .  # Ejecutamos flake8 en todo el directorio actual
      - run:
          name: Run Tests
          command: |
            pip install pytest pytest-cov
            pytest --cov=. tests/
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build Docker Image
          command: |
            docker build -t your-dockerhub-username/my-app:latest .
      - run:
          name: Push Docker Image to DockerHub
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push your-dockerhub-username/my-app:latest
      - run:
          name: GitGuardian Scan
          command: |
            pip install gitguardian
            ggshield scan path .  # Escaneamos el proyecto con GitGuardian

workflows:
  build-and-test:
    jobs:
      - build

