version: 2.1

executors:
  python-executor:
    docker:
      - image: circleci/python:3.8

jobs:
  build:
    executor: python-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Upgrade pip
          command: python -m pip install --upgrade pip
      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: Run Lint
          command: |
            pip install flake8
            flake8 src/
      - run:
          name: Run Tests
          command: |
            pip install pytest pytest-cov
            pytest --cov=src/ tests/
      - run:
          name: SonarCloud Scan
          command: |
            sonar-scanner
      - run:
          name: GitGuardian Scan
          command: |
            pip install gitguardian
            ggshield scan repo .

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
