version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.3

executors:
  python-executor:
    docker:
      - image: circleci/python:3.8

jobs:
  build:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Update pip
          command: |
            python -m pip install --upgrade pip  # Actualizamos pip a la versión más reciente
      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: Install SonarScanner
          command: |
            curl -sSLo sonar-scanner-cli.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
            unzip sonar-scanner-cli.zip
            echo 'export PATH=$PATH:$(pwd)/sonar-scanner-4.6.2.2472-linux/bin' >> $BASH_ENV
      - run:
          name: Install flake8
          command: |
            pip install flake8
      - run:
          name: Run Lint
          command: |
            flake8 .  # Ejecutamos flake8 en todo el directorio actual
      - run:
          name: Run Tests
          command: |
            pip install pytest pytest-cov
            pytest --cov=. tests/
      - run:
          name: SonarCloud Scanner
          command: |
            sonar-scanner -Dsonar.organization=voydelau28 -Dsonar.projectKey=voydelau28_practica_cicd -Dsonar.login=$SONAR_TOKEN

workflows:
  build-and-test:
    jobs:
      - build
