version: 2.1

executors:
  python-java-executor:
    docker:
      - image: cimg/openjdk:17.0  # Imagen con OpenJDK 17 preinstalado

jobs:
  build:
    executor: python-java-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Check Python version
          command: python3 --version  # Verifica si Python 3 está correctamente instalado
      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: Run Lint
          command: |
            pip install flake8
            flake8 .
      - run:
          name: Run Tests
          command: |
            pip install pytest pytest-cov
            pytest --cov=. tests/
      - run:
          name: Install SonarScanner
          command: |
            curl -sSLo /tmp/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
            unzip /tmp/sonar-scanner.zip -d /home/circleci
            export PATH=$PATH:/home/circleci/sonar-scanner-4.6.2.2472-linux/bin
      - run:
          name: SonarCloud Scan
          command: |
            /home/circleci/sonar-scanner-4.6.2.2472-linux/bin/sonar-scanner \
              -Dsonar.projectKey=voydelau28_practica_cicd \
              -Dsonar.organization=voydelau28 \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=$SONAR_TOKEN
      - run:
          name: GitGuardian Scan
          command: |
            pip install gitguardian
            ggshield scan repo .

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
