version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.3  # Asegúrate de tener la versión correcta de la orb

executors:
  python-executor:
    docker:
      - image: circleci/python:3.8

jobs:
  build:
    executor: python-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: Run Lint
          command: |
            pip install flake8
            flake8 .
      - run:
          name: Run Tests
          command: |
            pip install pytest pytest-cov
            pytest --cov=. tests/
      - run:
          name: SonarCloud Scanner
          command: |
            sonar-scanner -Dsonar.organization=voydelau28 -Dsonar.projectKey=voydelau28_practica_cicd -Dsonar.login=$SONAR_TOKEN

workflows:
  build-and-test:
    jobs:
      - build
