version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0

jobs:
  build:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Instalar dependencias
          command: |
            pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Ejecutar pruebas
          command: |
            pytest --cov=backend --cov-report xml:coverage.xml
      - run:
          name: Ejecutar linting
          command: |
            flake8 .
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: coverage.xml
      - sonarcloud/scan  # Solo se llama al comando sin argumentos específicos
      - run:
          name: Build Docker image
          command: docker build -t $DOCKERHUB_USERNAME/myapp:latest .
      - run:
          name: Test Docker image
          command: docker run --rm $DOCKERHUB_USERNAME/myapp:latest pytest

workflows:
  version: 2.1
  workflow_build:
    jobs:
      - build
