version: 2.1

executors:
  python-java-executor:
    docker:
      - image: cimg/python:3.8.14  # Imagen con Python 3.8 preinstalado
    environment:
      PIP_CACHE_DIR: ~/.cache/pip

jobs:
  build:
    executor: python-java-executor
    steps:
      - checkout
      
      # Restaurar caché de dependencias
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      
      # Instalación de dependencias
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt
      
      # Guardar caché de dependencias
      - save_cache:
          paths:
            - ~/.cache/pip
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # Lint del código
      - run:
          name: Run Lint
          command: |
            pip install flake8
            flake8 .
      
      # Ejecutar tests
      - run:
          name: Run Tests
          command: |
            pip install pytest pytest-cov
            pytest --cov=. tests/
      
      # Subir resultados de los tests
      - store_test_results:
          path: test-results
      
      # Subir informes de cobertura de los tests
      - store_artifacts:
          path: test-results
          
      # Guardar caché del workspace
      - persist_to_workspace:
          root: .
          paths:
            - test-results
            - .

      # SonarCloud Scan
      - run:
          name: Install SonarScanner
          command: |
            curl -sSLo /tmp/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
            unzip /tmp/sonar-scanner.zip -d /home/circleci
            export PATH=$PATH:/home/circleci/sonar-scanner-4.6.2.2472-linux/bin

      - run:
          name: SonarCloud Scan
          command: |
            /home/circleci/sonar-scanner-4.6.2.2472-linux/bin/sonar-scanner \
              -Dsonar.projectKey=voydelau28_practica_cicd \
              -Dsonar.organization=voydelau28 \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=$SONAR_TOKEN

      # Guardar caché
      - save_cache:
          paths:
            - ~/.sonar/cache
          key: v1-sonar-{{ checksum "sonar-project.properties" }}

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
