version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0

jobs:
  build:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - setup_remote_docker: {}   
    
      - run:
          name: Instalar dependencias
          command: |
            pip install --upgrade pip
            pip install -r requirements.txt httpx
      - run:
          name: Ejecutar pruebas
          command: |
            pytest --cov=backend --cov-report xml:coverage.xml
      - run:
          name: Ejecutar linting
          command: |
            flake8 .
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: coverage.xml
      - sonarcloud/scan  # Llamada al orb sin especificar parámetros en el archivo de configuración
      - run:
          name: Build Docker image
          command: docker build -t voydelau28/myapp:latest .
      - run:
          name: Test Docker image
          command: docker run --rm voydelau28/myapp:latest pytest

workflows:
  workflow_build:
    jobs:
      - build

