version: 2.1

executors:
  python-executor:
    docker:
      - image: circleci/python:3.8

jobs:
  build:
    executor: python-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Upgrade pip
          command: python -m pip install --upgrade pip
      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: Run Lint
          command: |
            pip install flake8
            flake8 .  # Reemplazar 'src/' con '.' para linting en la raíz del proyecto
      - run:
          name: Run Tests
          command: |
            pip install pytest pytest-cov
            pytest --cov=. tests/  # Cambiar cobertura a '.' para cubrir la raíz o el directorio correcto
      - run:
          name: Install SonarScanner
          command: |
            curl -sSLo /tmp/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
            unzip /tmp/sonar-scanner.zip -d /opt
            export PATH=$PATH:/opt/sonar-scanner-4.6.2.2472-linux/bin
      - run:
          name: SonarCloud Scan
          command: |
            sonar-scanner \
              -Dsonar.projectKey=voydelau28_practica_cicd \
              -Dsonar.organization=voydelau28 \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=$SONAR_TOKEN
      - run:
          name: GitGuardian Scan
          command: |
            pip install gitguardian
            ggshield scan repo .

workflows:
  version: 2
  build-and-test:
    jobs:
      - build

