version: 2.1

executors:
  python-sonar-executor:
    docker:
      - image: sonarsource/sonar-scanner-cli:latest  # Imagen con SonarScanner preinstalado

jobs:
  build:
    executor: python-sonar-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Python 3.8
          command: |
            sudo apt-get update
            sudo apt-get install -y python3.8 python3-pip
      - run:
          name: Install Dependencies
          command: |
            pip3 install -r requirements.txt
      - run:
          name: Run Lint
          command: |
            pip3 install flake8
            flake8 .
      - run:
          name: Run Tests
          command: |
            pip3 install pytest pytest-cov
            pytest --cov=. tests/
      - run:
          name: SonarCloud Scan
          command: |
            sonar-scanner \
              -Dsonar.projectKey=voydelau28_practica_cicd \
              -Dsonar.organization=voydelau28 \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=$SONAR_TOKEN
      - run:
          name: GitGuardian Scan
          command: |
            pip3 install gitguardian
            ggshield scan repo .

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
