apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: practica-cicd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/voydelau28/practica_cicd.git'
    targetRevision: main
    path: k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
